# Generated by Django 2.0.2 on 2019-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='设置不是HTML类型，可为空', max_length=500, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '展示'), (0, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
